sudo: false
language: generic

env:
  global:
      # HACKAGE_PASSWORD
    - secure: QIUcHq8VABK/keR2dGZHhbDuAwy8D+ewODLC5jfWgW35RvvWLkWQIezyqJF4/jJm6aouu9VFx7HpRBartMtuxPlLVvnpEdA2nONSr4pA6DD2pF8XcfX2ksPGHDgrdMVstQC6mL7mR6hZ7jEkcZXXGvnpCI/fC0yZEni1RfePKUXKJCWU3qPUjEv3s1nXxpIRykp4ld/B+miHZkAfhpxlHcxl6Dsl/CSWQU8NgDbM3dfbGKtcERzRuJmnxrsef4GRJebGlgIebgCw95zB+v6KoMD4OelNRrN5tAO2ZdQucWzo5wXh1xZCW3cX5JA4McyQjP/72nNOP7cIybDuJST1GhiyewX2yYiAnedMSv4DYc4P+2eiiFyFkRLBalWa5nCs7PtO3zVFNDzphodKkefocF63j3rdKAEmCoznE4TXCYNvjdJ/2LY0eeVHR67H1OAJGfrrnGA/doM2OGXrzTgmMdM4bFD5RQmezfT6XCsThb1L9u7Z74GwxWkAhmbOK8wz+L7/uvp5vw3jdbRqK41jfePeJmev0c5KRFN0sSrOZvuvskFrMxsJjeIqHpHMa5ztapJjLHzQ+pCTAYmVG0pRfVW0A+fR+/6OlXUgHF2WnrF523fgzuX3wT6rZFizQww5O8tC/IdEMsYMb5asMxq/8UI9/k8IG3pxaICdA90mqT4=

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

before_install:
  - curl -sSL https://get.haskellstack.org/ | sh
  - stack --version

install:
  - stack build --test --bench --only-dependencies

jobs:
  include:
    - stage: Build and test
      script: stack build --pedantic --test --bench --no-run-benchmarks
    - stage: Hackage deploy
      # n is for "store credentials" question
      # --pvp-bounds is broken in stack-2.3.1
      script: echo -e "ozzzzz\n${HACKAGE_PASSWORD}\nn" | stack upload .
      if: tag IS present
